on: [push, pull_request]
name: CI

jobs:
  Tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: rathdrumcfr_test
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo
          coverage: pcov

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Copy Env File
        run: cp .env.example .env

      - name: Generate App Key
        run: php artisan key:generate

      - name: Execute tests
        run: composer run coverage
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Run Linter
        run: ./vendor/bin/pint
